// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwzXu_1cHVNG8SXJM64WyRba33f6iR0Zw',
    appId: '1:429076960410:web:71e71a363a42d194a03b23',
    messagingSenderId: '429076960410',
    projectId: 'commerce-d45a4',
    authDomain: 'commerce-d45a4.firebaseapp.com',
    storageBucket: 'commerce-d45a4.appspot.com',
    measurementId: 'G-3KCY6TLBK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTHVQzUmkBBX6qjp8d10o67_DJDRwl7_k',
    appId: '1:429076960410:android:3e5920a956462e78a03b23',
    messagingSenderId: '429076960410',
    projectId: 'commerce-d45a4',
    storageBucket: 'commerce-d45a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiIP-XL1gnvi2F5txnBqHHgDcmnPTb4W8',
    appId: '1:429076960410:ios:ced5c4133254c07aa03b23',
    messagingSenderId: '429076960410',
    projectId: 'commerce-d45a4',
    storageBucket: 'commerce-d45a4.appspot.com',
    iosClientId: '429076960410-2c0e0t95r129d6opcdja36a9jv66bna6.apps.googleusercontent.com',
    iosBundleId: 'com.example.commerce',
  );
}
